### ISSUE TITLE
CLI Wizard: generate docker configuration

### ISSUE THREAD

**Issue by sdzyba** [luckyframework/lucky_cli#229]
It might worth to include a `Generate docker configuration for dev environment? [y/n]` during Lucky CLI Wizard setup.

Simple examples for API app:

Dockerfile
```
FROM crystallang/crystal:0.25.1

WORKDIR /
RUN git clone https://github.com/luckyframework/lucky_cli.git

WORKDIR /lucky_cli
RUN git checkout v0.11.0
RUN shards install
RUN crystal build src/lucky.cr --release --no-debug
RUN mv lucky /usr/local/bin

WORKDIR /app

COPY ./shard.yml ./shard.yml
COPY ./shard.lock ./shard.lock

RUN shards install

CMD ["lucky", "watch"]
```

.dockerignore
```
lib
bin
```

docker-compose.yml
```
version: "3.5"

services:
    app:
        image: lucky_app
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .:/app
            - lib:/app/lib/
        ports:
            - 5000:5000
        networks:
            local: {}

volumes:
    lib:
        driver: local

networks:
    local:
        driver: bridge
```
