### ISSUE TITLE
lucky init should strip invalid characters from project name

### ISSUE THREAD

**Issue by robacarp** [luckyframework/lucky_cli#248]
I was doing some cli hijinks trying to bootstrap a project with lucky into an existing folder and ended up running `lucky init project_name/` which had a bunch of weird side effects, for example:

```yml
# shard.yml
name: project_name/
version: 0.1.0

targets:
  project_name/:
    main: src/project_name/.cr

crystal: 0.26.0
```
