### ISSUE TITLE
Some way to run multiple tasks at once

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_cli#509]
Maybe this is with a lucky_cli.yaml file?

```yaml
aliases:
  db.setup:
    - db.create
    - db.migrate
    - db.create_required_seeds
```

And/or `lucky db.create,db.migrate,db.create_required_seeds`
